trigger: 
  branches:
    include:
    - features/*
    - main


pool: sumant2308

parameters:
- name: plan1
  type: string
  default: 'plan'
  values:
    - plan
    - apply
    - validate

steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'sumantserviceconnection2308'
    backendAzureRmResourceGroupName: '28sonujirg'
    backendAzureRmStorageAccountName: 'sonujistorage89'
    backendAzureRmContainerName: 'container34'
    backendAzureRmKey: 'sonuji31.tfstate'

- task: TerraformTask@5
  displayName: terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'sumantserviceconnection2308'

- task: TerraformTask@5
  displayName: terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'sumantserviceconnection2308'