name: delllaptop

on:
  workflow_dispatch:

jobs:
  terraform-job:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1.29.1
        with:
          path: .
          out: tfplan

      - name: Terraform Apply
        uses: dflook/terraform-apply@v1.29.1
        with:
          path: .
          plan: tfplan
          auto_approve: true
